ALTER TABLE products ADD COLUMN IF NOT EXISTS brand text;

UPDATE products SET brand = CASE
  WHEN name ILIKE 'Athavan%'       THEN 'Athavan'
  WHEN name ILIKE 'Araliya%'       THEN 'Araliya'
  WHEN name ILIKE 'Sri Ayyappa%'   THEN 'Sri Ayyappa'
  WHEN name ILIKE 'Ayyappa%'       THEN 'Ayyappa'
  WHEN name ILIKE 'Derana%'        THEN 'Derana'
  WHEN name ILIKE 'India Gate%'    THEN 'India Gate'
  WHEN name ILIKE 'Golden Crop%'   THEN 'Golden Crop'
  WHEN name ILIKE 'Malabar Treat%' THEN 'Malabar Treats'
  WHEN name ILIKE 'Grandma%'       THEN 'Grandma''s'
  WHEN name ILIKE 'Harischandra%'  THEN 'Harischandra'
  WHEN name ILIKE 'Katoomba%'      THEN 'Katoomba'
  WHEN name ILIKE 'KBT%'           THEN 'KBT'
  WHEN name ILIKE 'PATTU%'         THEN 'PATTU'
  WHEN name ILIKE 'Pattu%'         THEN 'PATTU'
  WHEN name ILIKE 'Shan%'          THEN 'Shan'
  WHEN name ILIKE 'Sjhan%'         THEN 'Shan'
  WHEN name ILIKE 'Leela%'         THEN 'Leela'
  WHEN name ILIKE 'KARA%'          THEN 'KARA'
  WHEN name ILIKE 'GRB%'           THEN 'GRB'
  WHEN name ILIKE 'TATA%'          THEN 'TATA'
  WHEN name ILIKE 'Viswas%'        THEN 'Viswas'
  WHEN name ILIKE 'Chakra%'        THEN 'Chakra'
  WHEN name ILIKE 'Fortune%'       THEN 'Fortune'
  WHEN name ILIKE 'PRAN%'          THEN 'PRAN'
  WHEN name ILIKE 'Kushi%'         THEN 'Kushi'
  WHEN name ILIKE 'Hamdard%'       THEN 'Hamdard'
  WHEN name ILIKE 'Sabrini%'       THEN 'Sabrini'
  WHEN name ILIKE 'Swetha%'        THEN 'Swetha'
  WHEN name ILIKE 'Uswalle%'       THEN 'Uswalle'
  WHEN name ILIKE 'Darena%'        THEN 'Darena'
  WHEN name ILIKE 'Delmege%'       THEN 'Delmege'
  WHEN name ILIKE 'Village%'       THEN 'Village'
  WHEN name ILIKE 'SIS%'           THEN 'SIS'
  WHEN name ILIKE 'MDK%'           THEN 'MDK'
  WHEN name ILIKE 'ICS%'           THEN 'ICS'
  WHEN name ILIKE 'Devaaya%'       THEN 'Devaaya'
  WHEN name ILIKE 'EuroFresh%'     THEN 'EuroFresh'
  WHEN name ILIKE 'Brahmins%'      THEN 'Brahmins'
  WHEN name ILIKE 'AMMAAS%'        THEN 'AMMAAS'
  WHEN name ILIKE 'Ammas%'         THEN 'AMMAAS'
  WHEN name ILIKE 'Ammaas%'        THEN 'AMMAAS'
  ELSE NULL
END;